name: Node CI

on:
  push:
    branches:
      - gh-pages
  pull_request: {}

jobs:
  ci:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install respec-validator
      - run: npx respec-validator --no-links --gh-user=${{ secrets.GH_USER }} --gh-token=${{ secrets.GH_TOKEN }} index.html
